language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
  - '7'
before_install:
  - npm update -g npm
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/vXXtr'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
